### PR TITLE
Reformatting nodes and links to use lines instead of curves between n…

### PR DESCRIPTION
**Pull request by dcombslinkedin**
…odes,

to offset links so there is a consistent distance away from the node,
use common separation between nodes vertically, and re-format the display
of each node into a box.

### CODE REVIEW

**Comment by dcombslinkedin** [comment]
Adding a screenshot of current display of the visualizer build tree itself.
screen shot 2017-12-25 at 4 48 12 pm

**Comment by rwjblue** [comment]
Awesome! Thanks for working on this!!

I’ll test this out locally when I’m back at my computer, but the screenshot looks great.

**Comment by dcombslinkedin** [comment]
Did some rework on the table display. Here's a screenshot of the latest pull-request files.
screen shot 2017-12-26 at 9 57 09 pm
screen shot 2017-12-26 at 9 57 51 pm

**Comment by dcombslinkedin** [comment]
I found an issue with trying to set the list of nodes while setting the map of node types. Will fix tomorrow or the next day (definitely before the weekend, but I have stuff going on tomorrow).
________________________________

**Comment by rwjblue** [comment]
Sounds good, thanks for working on this!

**Review by stefanpenner — APPROVED** [review]
LGTM!

**Comment by rwjblue** [comment]
Thank you!

**Comment by rwjblue** [comment]
Its live now, thank you again!

**Comment by dcombslinkedin** [comment]
Thanks, Robert! Let me know if there's anything else you'd like me to do with the visualizer or graph stuff.

**Pull request merged**
